[tasks.build]
command = "cargo"
args = ["build", "--target=wasm32-unknown-unknown", "--release"]

[tasks.format]
disabled = true

[tasks.test]
disabled = true

[tasks.post-build]
command = "cargo"
args = ["script", "post_build.rs"]