extern crate embed_js_build;

fn main() {
    use std::path::PathBuf;
    use std::fs::File;
    use std::io::{Write, BufWriter};

    // demonstration of support for js macro calls within files generated by a build script
    {
        let out_dir = PathBuf::from(std::env::var("OUT_DIR").unwrap());
        let mut writer = BufWriter::new(File::create(out_dir.join("generated_source.rs")).unwrap());
        write!(writer, r#"
pub fn foo() {{
    js!({{
        alert("Hello from generated source!");
    }});
}}
"#).unwrap();
    }

    // make sure to call embed_js_build::preprocess_crate *after* all generation is completed
    let root = PathBuf::from(std::env::var("CARGO_MANIFEST_DIR").unwrap()).join("src/lib.rs");
    embed_js_build::preprocess_crate(&root);

}
